### ISSUE TITLE
Inconsistent behavior in floor.reflectMarshaller when field is not in SchemaDefinition

### ISSUE THREAD

**Issue by ryanmiville** [fraugster/parquet-go#13]
When attempting to write a struct that contains fields not present in the `SchemaDefinition`, the `floor.reflectMarshaller` behaves inconsistently depending on the type of field in the struct it is decoding.

If it is a complex type (for example a `[]byte`), it will cause a panic because `schemaDef.SubSchema(fieldName)` will return a nil pointer which will later be unsafely dereferenced in the `decodeByteSliceOrArray` method.

However, simple primitives like bools will not cause a panic because there is no dereferencing. These will simply not be written, and `Write` will not return an `error`. I can see an argument for that to be the desired behavior, but as a user I expected an error in both cases, and regardless, the slice case should not cause a panic. 

## Reproduction steps
```go
package main

import (
	goparquet "github.com/fraugster/parquet-go"
	"github.com/fraugster/parquet-go/floor"
	"github.com/fraugster/parquet-go/parquet"
	"github.com/fraugster/parquet-go/parquetschema"
	"log"
)

func main() {
	obj1 := struct {Bar bool}{Bar: true}
	obj2 := struct {Bar []byte}{Bar: []byte{0xFF, 0x0A}}
	if err := write("bool.parquet", obj1); err != nil {
		log.Fatal(err)
	}
	if err := write("bytearray.parquet", obj2); err != nil {
		log.Fatal(err)
	}
}

func write(filename string, obj interface{}) error {
	schemaDef, err := parquetschema.ParseSchemaDefinition(`message test { required int32 foo; }`)
	if err != nil {
		return err
	}
	fw, err := floor.NewFileWriter(filename,
		goparquet.WithSchemaDefinition(schemaDef),
		goparquet.WithCompressionCodec(parquet.CompressionCodec_SNAPPY),
	)
	if err != nil {
		return err
	}
	if err := fw.Write(obj); err != nil { // panics when writing obj2
		return err
	}
	return fw.Close()
}
```

This program will write an empty `bool.parquet` file without returning an error, but will panic when writing `bytearray.parquet` with the following stack trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12131fd]

goroutine 1 [running]:
github.com/fraugster/parquet-go/floor.(*reflectMarshaller).decodeByteSliceOrArray(0xc00012a600, 0x12ca440, 0xc00012a660, 0x122e3a0, 0xc00012a500, 0x97, 0x0, 0xc00012a660, 0xc000056c10)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:222 +0x7d
github.com/fraugster/parquet-go/floor.(*reflectMarshaller).decodeValue(0xc00012a600, 0x12ca440, 0xc00012a660, 0x122e3a0, 0xc00012a500, 0x97, 0x0, 0x0, 0x0)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:202 +0x668
github.com/fraugster/parquet-go/floor.(*reflectMarshaller).decodeStruct(0xc00012a600, 0x12c7100, 0xc00011aea0, 0x1243980, 0xc00012a500, 0x99, 0xc0001320b8, 0x10, 0x124e0e0)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:110 +0x407
github.com/fraugster/parquet-go/floor.(*reflectMarshaller).marshal(...)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:79
github.com/fraugster/parquet-go/floor.(*reflectMarshaller).MarshalParquet(0xc00012a600, 0x12c7100, 0xc00011aea0, 0x0, 0x0)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:75 +0xc5
github.com/fraugster/parquet-go/floor.(*Writer).Write(0xc00012a5a0, 0x1243980, 0xc00012a500, 0x2, 0x2)
        /Users/ryanmiville/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/floor/writer.go:58 +0xf7
main.write(0x127f66d, 0x11, 0x1243980, 0xc00012a500, 0x0, 0x0)
        /Users/ryanmiville/projects/parquet/main/main.go:34 +0x105
main.main()
        /Users/ryanmiville/projects/parquet/main/main.go:17 +0x105

Process finished with exit code 2
```

**Comment by akrennmair** [comment]
This looks like it's been fixed a previous release. I added a unit test to cover this case. If the issue reappears, please feel free to open another ticket.
