### ISSUE TITLE
Error parsing schema from AWS Cost and Usage reporting file

### ISSUE THREAD

**Issue by davemac30** [fraugster/parquet-go#14]
Possibly the same as #12 I get similar when trying to parse the schema from a parquet file generated by AWS Cost and Usage Reporting:

```text
$ parquet-tool schema test-00001.snappy.parquet
panic: line 1: expected {, got unknown start of token '46' instead

goroutine 1 [running]:
github.com/fraugster/parquet-go.(*schema).GetSchemaDefinition(0xc000152300, 0xc00012a048)
	/Users/cml35/go/src/github.com/fraugster/parquet-go/schema.go:936 +0x7d
github.com/fraugster/parquet-go/cmd/parquet-tool/cmds.glob..func5(0x16174c0, 0xc000112ee0, 0x1, 0x1)
	/Users/cml35/go/src/github.com/fraugster/parquet-go/cmd/parquet-tool/cmds/schema.go:35 +0x1ac
github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra.(*Command).execute(0x16174c0, 0xc000112eb0, 0x1, 0x1, 0x16174c0, 0xc000112eb0)
	/Users/cml35/go/src/github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1616fc0, 0xc00004af78, 0x1007f25, 0xc000102058)
	/Users/cml35/go/src/github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/cml35/go/src/github.com/fraugster/parquet-go/vendor/github.com/spf13/cobra/command.go:864
github.com/fraugster/parquet-go/cmd/parquet-tool/cmds.Execute()
	/Users/cml35/go/src/github.com/fraugster/parquet-go/cmd/parquet-tool/cmds/root.go:16 +0x31
main.main()
	/Users/cml35/go/src/github.com/fraugster/parquet-go/cmd/parquet-tool/main.go:8 +0x25
```

In this case it looks like there's a problem with the root message id - `com.amazon.aws.origami.datawriter.parquet.ParquetDataWriter$`. Seems to be failing at the first '.' (0x46).

**Comment by davemac30** [comment]
this additional test case triggers the behaviour:

```diff --git a/parquetschema/schema_parser_test.go b/parquetschema/schema_parser_test.go
index 240ee31..a992490 100644
--- a/parquetschema/schema_parser_test.go
+++ b/parquetschema/schema_parser_test.go
@@ -486,6 +486,7 @@ message foo { }`, false, false}, // this is necessary because we once had a pars
 
 			}
 		}`, false, true}, // invalid ConvertedType
+		{`message foo.bar { }`, false, false}, // '.' (0x46) in message id
 	}
 
 	for idx, tt := range testData {
```
