### ISSUE TITLE
schema with non-alphanumeric identifier?

### ISSUE THREAD

**Issue by pwmcintyre** [fraugster/parquet-go#15]
hi

i like the look at your package and am doing a prototype for a project, but i have a unique requirement with a parquet file which contains a "."

i'm having trouble doing that, any advice?

example test:
```golang
package main

import (
	"io"
	"os"
	"testing"

	goparquet "github.com/fraugster/parquet-go"
	"github.com/fraugster/parquet-go/parquet"
	"github.com/fraugster/parquet-go/parquetschema"
)

const schema = `message test {
	optional binary version (UTF8);
	optional binary meta.id (UTF8);
}`

var data = map[string]interface{}{
	"version": []byte("v1"),
	"meta.id": []byte("01EWZYTXQHBYXEHZRC329X4QD3"),
}

func Test_Main(t *testing.T) {

	// parse schema
	s, err := parquetschema.ParseSchemaDefinition(schema)
	if err != nil {
		t.Fatalf("failed to parse schema: %v", err)
	}

	// create output file
	os.Remove("output.parquet")
	var f io.WriteCloser
	if f, err = os.OpenFile("output.parquet", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644); err != nil {
		t.Fatalf("failed to open file: %v", err)
	}
	defer f.Close()

	// create parquet writer
	fw := goparquet.NewFileWriter(f,
		goparquet.WithCompressionCodec(parquet.CompressionCodec_SNAPPY),
		goparquet.WithSchemaDefinition(s),
		goparquet.WithCreator("write-lowlevel"),
	)
	defer fw.Close()

	// write parquet
	if err := fw.AddData(data); err != nil {
		t.Errorf("failed to AddData: %v", err)
	}

}
```

produces this error:
```shell
./main_test.go:28: failed to parse schema: line 3: expected ;, got unknown start of token '46' instead
```

Similarly, if i attempt to read my existing file (produced by existing system), i can `cat` it but can't get `schema` — failing with the same error — eg.

```shell
$ parquet-tool cat ./example.parquet
version = v1
meta.id = 01EWZYTXQHBYXEHZRC329X4QD3
```

```shell
parquet-tool schema ./example.parquet
panic: line 3: expected ;, got unknown start of token '46' instead

goroutine 1 [running]:
github.com/fraugster/parquet-go.(*schema).GetSchemaDefinition(0xc00006c340, 0xc000010058)
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/schema.go:936 +0x7d
github.com/fraugster/parquet-go/cmd/parquet-tool/cmds.glob..func5(0x18365e0, 0xc00005af00, 0x1, 0x1)
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/cmd/parquet-tool/cmds/schema.go:35 +0x1ac
github.com/spf13/cobra.(*Command).execute(0x18365e0, 0xc00005aed0, 0x1, 0x1, 0x18365e0, 0xc00005aed0)
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x18360e0, 0xc000057f78, 0x100772f, 0xc00007a058)
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/fraugster/parquet-go/cmd/parquet-tool/cmds.Execute()
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/cmd/parquet-tool/cmds/root.go:16 +0x31
main.main()
        /Users/petermcintyre/go/1.14.7/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/cmd/parquet-tool/main.go:8 +0x20
```

**Comment by fzerorubigd** [comment]
this schema ```message test {
	optional binary version (UTF8);
	optional binary meta.id (UTF8);
}``` is invalid. 
it is translated to (roughly) 
```
message test {
	optional binary version (UTF8);
	optional group meta {
            binary id (UTF8);
       }
}
```
since dot in the name means nested column.

**Comment by pwmcintyre** [comment]
@fzerorubigd — when you say "is invalid" ... do you think it's invalid Parquet? or invalid for this package?

the parquet schema was created by a java implementation, but the Parquet schema in general is a bit vague

anyway, it doesn't matter, our schema is certainly unconventional and is causing us drama!

**Comment by fzerorubigd** [comment]
No, you are right, Parquet uses an array of strings in the column header, we use dot in our implementation. I am going to investigate if we can change it to another character (it can be an option) or maybe we can get rid of it completely
