### ISSUE TITLE
GetSchemaDefinition throws if there is array

### ISSUE THREAD

**Issue by iamorchid** [fraugster/parquet-go#41]
panic: line 1: expected {, got unknown start of token '46' instead [recovered]
	panic: line 1: expected {, got unknown start of token '46' instead

goroutine 19 [running]:
testing.tRunner.func1.2(0x124fce0, 0xc000099380)
	/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000082900)
	/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x124fce0, 0xc000099380)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/fraugster/parquet-go.(*schema).GetSchemaDefinition(0xc0000f4800, 0x10)
	/Users/will/go/pkg/mod/github.com/fraugster/parquet-go@v0.3.0/schema.go:936 +0x85

**Comment by iamorchid** [comment]
This is sample data in parquet file generated using Java:
{"id": 1, "Name": "emp1", "Dept": "D1", "mapField": {"key1": "val1", "key2": "val2"}, "loves": ["fishing", "reading"]}
{"id": 2, "Name": "emp2", "Dept": "D2", "mapField": {"key1": "val1", "key2": "val2"}, "loves": ["fishing", "reading"]}
{"id": 3, "Name": "emp3", "Dept": "D3", "mapField": {"key1": "val1", "key2": "val2"}, "loves": ["fishing", "reading"]}

**Comment by iamorchid** [comment]
The schema text looks like as below:
"message ns.empRecords {\n  required int32 id;\n  required binary Name (STRING);\n  required binary Dept (STRING);\n  required group mapField (MAP) {\n    repeated group key_value (MAP_KEY_VALUE) {\n      required binary key (STRING);\n      required binary value (STRING);\n    }\n  }\n  required group loves (LIST) {\n    repeated binary array (STRING);\n  }\n}\n"

**Comment by akrennmair** [comment]
Hi @iamorchid, I can't seem to reproduce the issue with the latest version (v0.4.0) of parquet-go. Another PR that relaxed the requirements for identifiers most likely fixed the issue. Can you please verify?
